import { useState } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

const Agregar = () => {

    const [numero_1, setNumberOne] = useState('')
    const [numero_2, setNumberTwo] = useState('')

    const router = useRouter()

    const handleSubmit = async e => {
        e.preventDefault()

        if ([numero_1, numero_2].includes(''))
            alert('Rellenar todos los campos.')

        let settings = {
            method: 'POST',
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({numero_1,  numero_2})
        }
        try {
            let fetchResponse = await fetch(`http://localhost:4000/users`, settings)
            let data = await fetchResponse.json()
            // console.log(data)
            router.push('/')
        } catch (error) {
            console.log(error)
        }
    }

    return (
        <>
            <Head>
                <title>Create Nuevo Usuario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <form className={styles.form} onSubmit={handleSubmit}>
                    <label htmlFor="first">Primer numero</label>
                    <input
                        className={styles.fields}
                        id="first"
                        type="text"
                        name="numero_1"
                        onChange={e => setNumberOne(+e.target.value)}
                        />

                    <label htmlFor="second">Segundo numero</label>
                    <input
                        type="text"
                        className={styles.fields}
                        id="second"
                        name="numero_2"
                        onChange={e => setNumberTwo(+e.target.value)}
                    />

                    <button className={styles.button}>Sumar</button>
                </form>
            </main>
        </>
    )
}

export default Agregar
